# Copy base settings
# Copies the base settings into the mizuRoute settings folder.

# modules
import pandas as pd
from pathlib import Path
from shutil import copyfile
from datetime import datetime

# --- Control file handling
# Easy access to control file folder
controlFolder = Path('../0_control_files')

# Store the name of the 'active' file in a variable
controlFile = 'control_active.txt'

# Function to extract a given setting from the control file
def read_from_control( file, setting ):
    
    # Open 'control_active.txt' and ...
    with open(file) as contents:
        for line in contents:
            
            # ... find the line with the requested setting
            if setting in line and not line.startswith('#'):
                break
    
    # Extract the setting's value
    substring = line.split('|',1)[1]      # Remove the setting's name (split into 2 based on '|', keep only 2nd part)
    substring = substring.split('#',1)[0] # Remove comments, does nothing if no '#' is found
    substring = substring.strip()         # Remove leading and trailing whitespace, tabs, newlines
       
    # Return this value    
    return substring
    
# Function to specify a default path
def make_default_path(suffix):
    
    # Get the root path
    rootPath = Path( read_from_control(controlFolder/controlFile,'root_path') )
    
    # Get the domain folder
    domainName = read_from_control(controlFolder/controlFile,'domain_name')
    domainFolder = 'domain_' + domainName
    
    # Specify the forcing path
    defaultPath = rootPath / domainFolder / suffix
    
    return defaultPath
    
    
# --- Find where the landclass is

rootPath = Path( read_from_control(controlFolder/controlFile,'root_path') )
domainName = read_from_control(controlFolder/controlFile,'domain_name')

# CAMELS-spath
CAMELS_spath = read_from_control(controlFolder/controlFile,'camels_spath')

# Specify default path if needed
if CAMELS_spath == 'default':
    CAMELS_spath = rootPath / 'CAMELS-spat'
else:
    CAMELS_spath = Path(CAMELS_spath) # make sure a user-specified path is a Path()
    
# Metadata
metadata_path = CAMELS_spath
metadata_name = "camels-spat-metadata.csv"

df_metadata = pd.read_csv(metadata_path / metadata_name)


country, station_id = domainName.split("_")

# Get categories 
category_value = df_metadata.loc[(df_metadata['Country'] == country) & (df_metadata['Station_id'] == station_id), 'subset_category']

# Ensure category_value is a string
if not category_value.empty:
    category_value = category_value.iloc[0]  # Convert Series to string
else:
    raise ValueError("No matching subset category found.")  # Handle missing value    

# Landclass
landclass_file_path =  CAMELS_spath / 'geospatial' / category_value / 'modis-land' / domainName
landclass_file_name = domainName + '_2001_2022_mode_MCD12Q1_LC_Type1.tif'


# --- Find where the landclass will be

parameter_landclass_mode_path = read_from_control(controlFolder/controlFile,'parameter_land_mode_path')
parameter_landclass_tif_name = read_from_control(controlFolder/controlFile,'parameter_land_tif_name')

# Specify default path if needed
if parameter_landclass_mode_path == 'default':
    parameter_landclass_mode_path = make_default_path('parameters/landclass/7_mode_land_class') # outputs a Path()
else:
    parameter_landclass_mode_path = Path(parameter_landclass_mode_path) # make sure a user-specified path is a Path()

# Make the folder if it doesn't exist
parameter_landclass_mode_path.mkdir(parents=True, exist_ok=True)


# --- Copy the landclass from CAMELS-spat database to parameters folder

    
copyfile(landclass_file_path / landclass_file_name, parameter_landclass_mode_path / parameter_landclass_tif_name);

    
# --- Code provenance
# Generates a basic log file in the domain folder and copies the control file and itself there.

# Set the log path and file name
logPath = parameter_landclass_mode_path
log_suffix = '_make_landclasstiff.txt'

# Create a log folder
logFolder = '_workflow_log'
Path( logPath / logFolder ).mkdir(parents=True, exist_ok=True)

# Copy this script
thisFile = '2_make_landclasstiff.py'
copyfile(thisFile, logPath / logFolder / thisFile);

# Get current date and time
now = datetime.now()

# Create a log file 
logFile = now.strftime('%Y%m%d') + log_suffix
with open( logPath / logFolder / logFile, 'w') as file:
    
    lines = ['Log generated by ' + thisFile + ' on ' + now.strftime('%Y/%m/%d %H:%M:%S') + '\n',
             'Copy CAMELS-spat landclass to current workflow.']
    for txt in lines:
        file.write(txt) 