# GDAL doc: https://gdal.org/programs/gdalwarp.html
# MODIS doc: https://lpdaac.usgs.gov/documents/101/MCD12_User_Guide_V6.pdf

# Reprojects the VRTs with MODIS data into EPSG:4326, which the rest of the workflow is based on.

module load gdal


#---------------------------------
# Specify settings
#---------------------------------

# --- Location of raw data
dest_line=$(grep -m 1 "parameter_land_vrt1_path" ../../../0_control_files/control_active.txt) # full settings line
source_path=$(echo ${dest_line##*|})   # removing the leading text up to '|'
source_path=$(echo ${source_path%% #*}) # removing the trailing comments, if any are present

# Specify the default path if needed
if [ "$source_path" = "default" ]; then
  
 # Get the root path and append the appropriate install directories
 root_line=$(grep -m 1 "root_path" ../../../0_control_files/control_active.txt)
 root_path=$(echo ${root_line##*|}) 
 root_path=$(echo ${root_path%% #*})

 # domain name
 domain_line==$(grep -m 1 "domain_name" ../../../0_control_files/control_active.txt)
 domain_name=$(echo ${domain_line##*|}) 
 domain_name=$(echo ${domain_name%% #*})
 
 # source path
 source_path="${root_path}/domain_${domain_name}/parameters/landclass/2_vrt_native_crs"

fi

# --- Location where converted data needs to go
dest_line=$(grep -m 1 "parameter_land_vrt2_path" ../../../0_control_files/control_active.txt) # full settings line
dest_path=$(echo ${dest_line##*|})   # removing the leading text up to '|'
dest_path=$(echo ${dest_path%% #*}) # removing the trailing comments, if any are present

# Specify the default path if needed
if [ "$dest_path" = "default" ]; then
  
 # Get the root path and append the appropriate install directories
 root_line=$(grep -m 1 "root_path" ../../../0_control_files/control_active.txt)
 root_path=$(echo ${root_line##*|}) 
 root_path=$(echo ${root_path%% #*})

 # domain name
 domain_line==$(grep -m 1 "domain_name" ../../../0_control_files/control_active.txt)
 domain_name=$(echo ${domain_line##*|}) 
 domain_name=$(echo ${domain_name%% #*})
 
 # destination path
 dest_path="${root_path}/domain_${domain_name}/parameters/landclass/3_vrt_epsg_4326"
fi

# Make destination directory 
mkdir -p $dest_path


# --- Define the projection to use
PROJ="EPSG:4326"

#---------------------------------
# Reproject
#---------------------------------

# Loop over all vrt files in PATH_SRC 
for FILE_SRC in $source_path/MCD*.vrt
do
	
	# extract the file name
	FILENAME=$(basename -- $FILE_SRC)

	# construct the destination file
	FILE_DES=$dest_path/$FILENAME

	# do the warping
	gdalwarp -of VRT -t_srs $PROJ $FILE_SRC $FILE_DES

done


#---------------------------------
# Code provenance
#---------------------------------
# Generates a basic log file in the domain folder and copies the control file and itself there.
# Make a log directory if it doesn't exist
log_path="${dest_path}/_workflow_log"
mkdir -p $log_path

# Log filename
today=`date '+%F'`
log_file="${today}_compile_log.txt"

# Make the log
this_file='reproject_vrt.sh'
echo "Log generated by ${this_file} on `date '+%F %H:%M:%S'`"  > $log_path/$log_file # 1st line, store in new file
echo 'Reprojected VRTs into EPSG:4326.' >> $log_path/$log_file # 2nd line, append to existing file

# Copy this file to log directory
cp $this_file $log_path